name: featurehub_cli_example
version: 1.0.0
description: Example client for SDK
homepage: https://featurehub.io
publish_to: none
environment:
  sdk: ">=3.3.2 <4.0.0"
dependencies:
  dio: ^5.7.0
  logging: ^1.0.1
  featurehub_client_sdk:
    path: ../..
#dev_dependencies:
